<template><div class="container faq-page"><h1>{{ isZh ? '常见问题' : 'Frequently asked questions' }}</h1><p>{{ isZh ? '购买、配送和售后的实用信息。' : 'Practical information for shopping, delivery and support.' }}</p><details v-for="item in items" :key="item[0]"><summary>{{ item[0] }}</summary><p>{{ item[1] }}</p></details><NuxtLink to="/pages/contact-us">{{ isZh ? '还有问题？联系 CBJJ 客服' : 'Need more help? Contact CBJJ support' }} →</NuxtLink></div></template>
<script setup lang="ts">
import { computed } from 'vue'
const { isZh } = useShopLocale()
const items = computed(() => isZh.value ? [
['配送到哪些地区？','目前支持美国、加拿大及中国大陆，标准配送免运费。'],['发货及送达需要多久？','现货订单付款确认后 1–3 个工作日发货；美国及加拿大预计运输 5–10 个工作日，中国大陆预计 3–7 个工作日。'],['是否支持预售？','目前仅销售现货，不接受预售或缺货预订。'],['币种如何选择？','美国及加拿大配送订单使用 USD，中国大陆使用 CNY。语言切换不改变销售地区或已有订单币种。'],['可以使用 Klarna 吗？','目前尚未开通 Klarna 收款，可在关于 Klarna 页面查看官方介绍、客服及隐私信息。'],['如何退货或申请保修？','签收后 30 天内可申请退货，提供一年有限保修。请先通过 1479030891@qq.com 联系客服，取得处理指引。'],['可以在道路上骑行吗？','请查阅商品说明书并遵守所在地法规，商品展示及参数不代表获得特定地区道路使用许可。']
] : [
['Where do you deliver?','We deliver to the US, Canada and mainland China with free standard shipping.'],['How long does delivery take?','In-stock orders dispatch 1–3 business days after payment confirmation. Estimated transit is 5–10 business days to the US and Canada, or 3–7 to mainland China.'],['Do you accept pre-orders?','No. We sell in-stock products and do not accept pre-orders or backorders.'],['Which currency applies?','US and Canadian delivery orders use USD, mainland China orders use CNY. Language is separate from sales market and does not change an existing order’s currency.'],['Can I pay with Klarna?','Klarna is not yet enabled. See our About Klarna page for official information, support and privacy links.'],['How do returns and warranty work?','Request a return within 30 days of delivery. Products have a one-year limited warranty. Email 1479030891@qq.com before returning anything.'],['Can I ride on public roads?','Read the manual and follow local laws. A product listing or specification does not establish road-use approval in your jurisdiction.']
])
useSeoMeta({ title: 'FAQ | CBJJ' })
</script>
<style scoped>.faq-page{max-width:900px;padding-top:52px;padding-bottom:72px}.faq-page h1{font-size:40px;margin-bottom:18px}.faq-page>p{line-height:1.8;margin-bottom:28px;color:#4e5946}.faq-page details{border-top:1px solid #d9e1d2;padding:20px 0}.faq-page summary{font-size:18px;font-weight:700;cursor:pointer;line-height:1.5}.faq-page details p{line-height:1.9;margin-top:14px;color:#4e5946}.faq-page>a{display:inline-block;margin-top:30px;color:#397c0c;font-weight:700}summary:focus-visible,a:focus-visible{outline:3px solid #397c0c;outline-offset:3px}</style>
