<template>
  <Teleport to="body"><div v-if="isOpen" class="modal-overlay" @click.self="emit('close')"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="address-modal-title"><header><h2 id="address-modal-title">{{ isZh ? '新增收货地址' : 'Add shipping address' }}</h2><button type="button" :aria-label="t('close')" @click="emit('close')">×</button></header><form @submit.prevent="save"><label>{{ t('country') }}<select v-model="form.country" required><option value="US">{{ isZh ? '美国' : 'United States' }}</option><option value="CA">{{ isZh ? '加拿大' : 'Canada' }}</option><option value="CN">{{ isZh ? '中国大陆' : 'Mainland China' }}</option></select></label><div class="form-grid"><label v-for="field in fields" :key="field.key">{{ field.label }}<input v-model="form[field.key]" :autocomplete="field.autocomplete" :type="field.key === 'phone' ? 'tel' : 'text'" :required="field.key !== 'apartment'" maxlength="200" /></label></div><label class="checkbox"><input v-model="form.isDefault" type="checkbox" />{{ isZh ? '设为默认地址' : 'Set as default address' }}</label><footer><button type="button" @click="emit('close')">{{ isZh ? '取消' : 'Cancel' }}</button><button type="submit">{{ t('saveAddress') }}</button></footer></form></section></div></Teleport>
</template>
<script setup lang="ts">
import { computed, reactive, watch, onBeforeUnmount } from 'vue'
import { setPageScrollLocked, clearPageScrollLock } from '~/utils/scrollLock'
const props=defineProps<{ isOpen:boolean }>()
const emit=defineEmits(['close','save'])
const {isZh,t}=useShopLocale()
const {market}=useShopMarket()
const form=reactive<Record<string,any>>({country:market.value,firstName:'',lastName:'',address:'',apartment:'',city:'',state:'',zipCode:'',phone:'',isDefault:false})
const fields=computed(() => [{key:'firstName',label:t('firstName'),autocomplete:'given-name'},{key:'lastName',label:t('lastName'),autocomplete:'family-name'},{key:'address',label:t('addressLine1'),autocomplete:'address-line1'},{key:'apartment',label:t('addressLine2'),autocomplete:'address-line2'},{key:'city',label:t('city'),autocomplete:'address-level2'},{key:'state',label:t('state'),autocomplete:'address-level1'},{key:'zipCode',label:t('zipCode'),autocomplete:'postal-code'},{key:'phone',label:t('phone'),autocomplete:'tel'}])
watch(() => props.isOpen, value => setPageScrollLocked(value))
onBeforeUnmount(clearPageScrollLock)
const save=() => { emit('save',{...form}); emit('close') }
</script>
<style scoped>.modal-overlay{position:fixed;inset:0;z-index:1000;background:#0008;display:grid;place-items:center;padding:18px}.modal-card{width:min(600px,100%);max-height:90svh;overflow:auto;background:white;border-radius:12px;padding:24px}.modal-card header,.modal-card footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px}.modal-card h2{font-size:22px}.modal-card label{display:grid;gap:7px;font-size:14px}.modal-card input,.modal-card select{border:1px solid #bbb;border-radius:5px;padding:11px;width:100%;font:inherit}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}.modal-card .checkbox{display:flex;align-items:center;margin:20px 0}.checkbox input{width:auto}.modal-card button{padding:10px 16px;border:1px solid #777;border-radius:5px;background:white;cursor:pointer}.modal-card button[type=submit]{background:#203416;color:white;border-color:#203416}.modal-card :focus-visible{outline:3px solid #39850c;outline-offset:3px}@media(max-width:480px){.form-grid{grid-template-columns:1fr}.modal-card{padding:20px}}</style>
