<template>
  <footer class="app-footer">
    <section class="service-strip container"><div v-for="item in services" :key="item[0]"><strong>{{ item[0] }}</strong><span>{{ item[1] }}</span></div></section>
    <div class="container footer-main"><div class="footer-brand"><NuxtLink to="/" class="brand-wordmark">CBJJ<span>POWER YOUR EVERYDAY</span></NuxtLink><p>{{ isZh ? '为日常通勤与休闲骑行，选择适合自己的电动出行装备。' : 'Electric mobility for everyday journeys. Find the ride that fits your day.' }}</p><p>{{ brand.operator }}</p><a :href="`mailto:${brand.email}`">{{ brand.email }}</a><a :href="`tel:${brand.phoneHref}`">{{ brand.phone }}</a><NuxtLink to="/pages/contact-us">{{ isZh ? '公司地址及联系方式' : 'Company address & contact' }} →</NuxtLink></div><div v-for="group in groups" :key="group.title" class="footer-column"><h3>{{ group.title }}</h3><NuxtLink v-for="link in group.links" :key="link.to" :to="link.to">{{ link.label }}</NuxtLink></div></div>
    <div class="container footer-bottom"><p>© {{ new Date().getFullYear() }} CBJJ</p><MarketSelector /><div class="payment-logos" aria-label="Payment provider information"><img src="/cbjj/payments/visa.png" alt="Visa" loading="lazy" /><img src="/cbjj/payments/mastercard.svg" alt="Mastercard" loading="lazy" /><NuxtLink to="/pages/klarna"><img src="/cbjj/payments/klarna.svg" alt="About Klarna" loading="lazy" /></NuxtLink></div><small>{{ isZh ? '支付标识仅作信息展示；实际可用渠道以结算页为准。Klarna 尚未开通。' : 'Payment logos are informational. Checkout shows available methods. Klarna is not yet enabled.' }}</small></div>
  </footer>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { brand } from '~/data/brand'
const { isZh } = useShopLocale()
const services = computed(() => isZh.value ? [['标准配送免运费','美国、加拿大及中国大陆'],['现货发货','1–3 个工作日处理'],['30 天退货申请','详见退换货政策'],['一年有限保修','详见保修范围']] : [['Free standard shipping','US, Canada & mainland China'],['In-stock dispatch','1–3 business days processing'],['30-day return requests','See our returns policy'],['1-year limited warranty','See coverage and exclusions']])
const link = (en:string, zh:string, to:string) => ({ label: isZh.value ? zh : en, to })
const groups = computed(() => [
  { title: isZh.value ? '选购' : 'SHOP', links: [link('Electric scooters','电动滑板车','/collections/electric-scooters'),link('Electric bikes','电动自行车','/collections/electric-bike'),link('Electric skateboards','电动滑板','/collections/electric-skateboard'),link('Accessories','配件','/collections/accessories')] },
  { title: isZh.value ? '服务与政策' : 'SUPPORT', links: [link('Shipping policy','配送政策','/pages/shipping-policy'),link('Returns & refunds','退换货与退款','/pages/refund-policy'),link('Warranty','有限保修','/pages/warranty'),link('Order status','订单查询','/account/orders'),link('Payment methods','支付方式','/pages/payment-methods'),link('About Klarna / Pay later','关于 Klarna / 分期服务','/pages/klarna'),link('FAQ','常见问题','/pages/support-faq')] },
  { title: isZh.value ? '关于我们' : 'COMPANY', links: [link('About CBJJ','关于 CBJJ','/pages/about-us-1'),link('Contact us','联系我们','/pages/contact-us'),link('Terms of service','服务条款','/pages/terms-of-service'),link('Privacy policy','隐私政策','/pages/privacy-policy'),link('Official sales channels','官方销售渠道说明','/pages/authorized-sales'),link('Become a dealer','经销合作','/pages/become-a-dealer'),link('Affiliate partnerships','联盟推广合作','/pages/affiliate-program')] },
])
</script>
<style scoped lang="scss">
.app-footer{background:#1c211a;color:#f7f8f6}.service-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;padding:28px 0;border-bottom:1px solid #41483b}.service-strip div{display:grid;gap:7px}.service-strip strong{font-size:16px}.service-strip span{font-size:13px;color:#c8d2c1}.footer-main{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr;gap:36px;padding-top:42px;padding-bottom:42px}.brand-wordmark{font-size:38px;font-weight:900;letter-spacing:2px;line-height:1}.brand-wordmark span{display:block;font-size:10px;letter-spacing:2px;margin-top:12px;color:#b7e58f}.footer-brand{display:grid;gap:14px;align-content:start}.footer-brand p{font-size:13px;line-height:1.8;color:#c8d2c1}.footer-brand a{font-size:14px;overflow-wrap:anywhere}.footer-column{display:grid;align-content:start;gap:13px}.footer-column h3{font-size:14px;margin-bottom:8px;letter-spacing:1px}.footer-column a{font-size:13px;line-height:1.5;color:#d3ddcc}.app-footer a:hover{color:#b7e58f}.app-footer a:focus-visible{outline:3px solid #b7e58f;outline-offset:4px}.footer-bottom{display:flex;flex-wrap:wrap;align-items:center;gap:24px;padding-top:22px;padding-bottom:24px;border-top:1px solid #41483b}.footer-bottom p{font-size:12px}.footer-bottom small{flex-basis:100%;font-size:11px;color:#c8d2c1;line-height:1.6}.payment-logos{display:flex;align-items:center;gap:8px;margin-left:auto}.payment-logos img{width:52px;height:30px;object-fit:contain;background:#fff;border-radius:4px;padding:3px}@media(max-width:900px){.footer-main{grid-template-columns:repeat(2,1fr)}.service-strip{grid-template-columns:repeat(2,1fr);padding-left:20px;padding-right:20px}}@media(max-width:480px){.footer-main{gap:26px 18px}.footer-brand{grid-column:1/-1}.footer-column:last-child{grid-column:1/-1}.payment-logos{margin-left:0}}
</style>
