<template>
  <div class="cbjj-home">
    <section class="home-hero"><img src="/cbjj/hero/hero.png" :alt="isZh ? 'CBJJ 电动出行装备展示' : 'CBJJ electric mobility showcase'" fetchpriority="high" /><div class="container hero-content"><span class="eyebrow">CBJJ · POWER YOUR EVERYDAY</span><h1>{{ isZh ? '让每一天，\n骑得更自在。' : 'Your everyday.\nElectrified.' }}</h1><p>{{ isZh ? '从城市通勤到周末出游，发现适合你的电动滑板车、自行车和骑行配件。' : 'From your daily commute to a weekend outdoors, discover electric scooters, bikes and riding essentials.' }}</p><NuxtLink to="/collections/all" class="hero-cta">{{ isZh ? '探索全部商品' : 'Explore the collection' }} →</NuxtLink></div></section>
    <section class="container home-collections"><div class="section-heading"><span class="eyebrow">{{ isZh ? '找到你的出行方式' : 'FIND YOUR RIDE' }}</span><h2>{{ isZh ? '为你的日常而选' : 'A ride for every day' }}</h2></div><div class="category-grid"><NuxtLink v-for="item in categories" :key="item.slug" :to="`/collections/${item.slug}`"><img :src="item.heroImage" :alt="item.name" loading="lazy" /><h3>{{ item.name }}</h3><span>{{ isZh ? '查看商品' : 'Discover' }} →</span></NuxtLink></div></section>
    <section class="container home-products"><div class="section-heading"><span class="eyebrow">CBJJ COLLECTION</span><h2>{{ isZh ? '发现更多骑行选择' : 'Find your next ride' }}</h2><NuxtLink to="/collections/all">{{ isZh ? '查看全部' : 'View all' }} →</NuxtLink></div><div class="product-grid"><ProductCard v-for="product in products" :key="product.id" :product="product" /></div><p v-if="!products.length">{{ isZh ? '商品暂不可用，请稍后再试。' : 'Products are temporarily unavailable. Please try again shortly.' }}</p></section>
    <section class="home-support"><div class="container support-grid"><div><span class="eyebrow">{{ isZh ? '买得清楚，骑得安心' : 'CLEAR INFORMATION. CONFIDENT CHOICES.' }}</span><h2>{{ isZh ? '购买前，了解每一步。' : 'Know what to expect.' }}</h2><p>{{ isZh ? '发货时效、退货流程、保修支持及支付方式，都在这里。' : 'Delivery times, returns, warranty support and payment information, all in one place.' }}</p></div><div class="support-links"><NuxtLink to="/pages/shipping-policy">{{ isZh ? '配送与运费' : 'Shipping & delivery' }} →</NuxtLink><NuxtLink to="/pages/refund-policy">{{ isZh ? '退换货与退款' : 'Returns & refunds' }} →</NuxtLink><NuxtLink to="/pages/klarna">{{ isZh ? '了解 Klarna' : 'Learn about Klarna' }} →</NuxtLink><NuxtLink to="/pages/contact-us">{{ isZh ? '联系 CBJJ 客服' : 'Contact CBJJ support' }} →</NuxtLink></div></div></section>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue'
const { isZh, lang } = useShopLocale()
const { currency } = useShopMarket()
const { data } = await useAsyncData(`cbjj-home-${lang.value}-${currency.value}`, async () => {
  const [catalog, categoryResponse] = await Promise.all([useHttp('/api/product/list', { query: { pageSize: 8 }, showError: false }), useHttp('/api/category/tree', { showError: false })])
  return { products: catalog?.data?.records || [], categories: categoryResponse?.data || [] }
})
const products = computed(() => data.value?.products || [])
const categories = computed(() => (data.value?.categories || []).filter((item:any) => !item.parentId).slice(0,4))
useSeoMeta({ title: 'CBJJ | Electric scooters, bikes & riding essentials', description: () => isZh.value ? '探索 CBJJ 电动滑板车、电动自行车、电动滑板及骑行配件，查看完整配送及售后政策。' : 'Discover CBJJ electric scooters, bikes, skateboards and riding essentials, with clear delivery and after-sales policies.' })
</script>
<style scoped lang="scss">
.home-hero{position:relative;min-height:620px;background:#eff1ec;overflow:hidden}.home-hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.home-hero::after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(242,245,235,.97),rgba(242,245,235,.82) 37%,transparent 68%)}.hero-content{position:relative;z-index:1;padding-top:95px;padding-bottom:85px}.eyebrow{font-size:11px;letter-spacing:2px;color:#326d0c;font-weight:800}.hero-content h1{white-space:pre-line;font-size:clamp(42px,6.5vw,82px);line-height:1.02;letter-spacing:-2px;margin:24px 0;max-width:620px}.hero-content p{max-width:440px;font-size:17px;line-height:1.75;color:#454f3d}.hero-cta{display:inline-block;background:#1f2919;color:white;padding:16px 26px;margin-top:30px;font-weight:700;border-radius:5px}.home-collections,.home-products{padding-top:62px;padding-bottom:50px}.section-heading{margin-bottom:28px}.section-heading h2{font-size:clamp(28px,3vw,40px);margin:12px 0}.section-heading>a{color:#326d0c;font-weight:600}.category-grid,.product-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}.category-grid>a{background:#f3f5f0;border-radius:10px;overflow:hidden;padding-bottom:24px}.category-grid img{width:100%;height:230px;object-fit:contain}.category-grid h3,.category-grid span{display:block;margin:12px 20px 0}.category-grid span{font-size:13px;color:#326d0c}.home-support{background:#eef2e6;padding:60px 0}.support-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:60px}.support-grid h2{font-size:38px;line-height:1.15;margin:16px 0}.support-grid p{line-height:1.8;color:#4e5946}.support-links{display:grid;gap:12px}.support-links a{background:white;padding:18px 22px;border-radius:7px;font-weight:600}a:hover{filter:brightness(.94)}a:focus-visible{outline:3px solid #397c0c;outline-offset:4px}@media(max-width:900px){.category-grid,.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.home-hero{min-height:540px}.support-grid{gap:30px}.hero-content h1{max-width:450px}}@media(max-width:600px){.home-hero{min-height:550px}.home-hero::after{background:linear-gradient(180deg,rgba(242,245,235,.97),rgba(242,245,235,.86) 50%,rgba(242,245,235,.4))}.hero-content{padding-top:45px;padding-bottom:50px}.hero-content h1{font-size:46px;letter-spacing:-1px}.hero-content p{font-size:15px}.home-collections,.home-products{padding-top:38px;padding-bottom:32px}.category-grid,.product-grid{gap:12px}.category-grid img{height:150px}.category-grid h3{font-size:16px;margin-left:14px}.support-grid{grid-template-columns:1fr}.support-grid h2{font-size:32px}}
</style>
