import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
import { chromium } from 'playwright'
const base='http://127.0.0.1:3000'
const browser=await chromium.launch({headless:true})
const context=await browser.newContext({viewport:{width:390,height:844}})
await context.addCookies([{name:'lang',value:'en',url:base},{name:'shop-market',value:'US',url:base}])
const errors=[];const api=[]
let requestSequence=0
const latestPreview=()=>api.filter(item=>item.path==='/order/preview').sort((a,b)=>a.sequence-b.sequence).at(-1)?.data
await context.route('https://fonts.googleapis.com/**',r=>r.abort())
await context.route('https://fonts.gstatic.com/**',r=>r.abort())
await context.route('**/api/**',async route=>{
 const sequence=++requestSequence
 const url=new URL(route.request().url());url.host='127.0.0.1:8081';url.pathname=url.pathname.replace(/^\/api/,'')
 const response=await route.fetch({url:url.toString()});const body=await response.json().catch(()=>null)
 api.push({sequence,path:url.pathname,query:url.search,code:body?.code,data:['/order/preview','/cart/list','/payment/methods'].includes(url.pathname)?body?.data:undefined})
 await route.fulfill({response})
})
const page=await context.newPage();page.on('pageerror',error=>errors.push(String(error)))
const result={}
try {
 await page.goto(base+'/login',{waitUntil:'domcontentloaded'})
 await page.locator('#email').fill('admin@isinwheel.local')
 await page.locator('#password').fill('123456')
 await page.locator('button.auth-submit').click()
 await page.waitForURL(base+'/',{timeout:10000})
 await page.goto(base+'/account/profile',{waitUntil:'domcontentloaded'})
 await page.waitForTimeout(1000)
 result.login=await page.locator('.identity-panel').innerText()
 assert.ok(result.login.includes('admin@isinwheel.local'),'Authenticated account should load')
 const cookie=(await context.cookies()).find(item=>item.name==='token')
 let token=decodeURIComponent(cookie.value);try{token=JSON.parse(token)}catch{}
 const cartResponse=await context.request.get('http://127.0.0.1:8081/cart/list',{headers:{Authorization:token}})
 for(const item of (await cartResponse.json()).data || []) await context.request.delete('http://127.0.0.1:8081/cart/'+item.cartItemId,{headers:{Authorization:token}})
 await page.goto(base+'/products/1',{waitUntil:'domcontentloaded'})
 await page.locator('.product-info .btn-add-to-cart').click()
 await page.waitForTimeout(700)
 await page.goto(base+'/checkout',{waitUntil:'domcontentloaded'})
 await page.waitForTimeout(600)
 await page.locator('.btn-select-address, .selected-address-card .ghost-btn').first().click()
 await page.locator('.saved-addresses-modal button.secondary-btn').click()
 await page.waitForTimeout(300)
 for(const [id,value] of Object.entries({firstName:'Alex',lastName:'Chen',addressLine1:'10 QA Street',city:'Toronto',state:'Ontario',zipCode:'M5V 1A1',phone:'+14155550123'})) await page.locator('#checkout-'+id).fill(value)
 await page.locator('#checkout-country').selectOption('CA')
 await page.waitForTimeout(700)
 result.canada=latestPreview()
 assert.equal(result.canada?.currency,'USD')
 assert.equal(result.canada?.totalAmount,269.99)
 await page.locator('#checkout-coupon').selectOption('1')
 await page.waitForTimeout(500)
 result.couponUSD=latestPreview()
 assert.equal(result.couponUSD?.discountAmount,10)
 assert.equal(result.couponUSD?.totalAmount,259.99)
 await page.locator('#checkout-country').selectOption('CN')
 await page.waitForTimeout(900)
 result.china=latestPreview()
 assert.equal(result.china?.currency,'CNY')
 assert.equal(result.china?.totalAmount,1889.93)
 await page.locator('#checkout-coupon').selectOption('1')
 await page.waitForTimeout(500)
 result.couponCNY=latestPreview()
 assert.equal(result.couponCNY?.discountAmount,70)
 assert.equal(result.couponCNY?.totalAmount,1819.93)
 result.paymentDisabled=await page.locator('.pay-now-btn').isDisabled()
 assert.ok(result.paymentDisabled)
 result.cardFields=await page.locator('input[autocomplete=cc-number]').count()
 assert.equal(result.cardFields,0)
 await page.locator('#checkout-city').fill('')
 await page.waitForTimeout(250)
 result.invalidAddressDisabled=await page.locator('.pay-now-btn').isDisabled()
 assert.ok(result.invalidAddressDisabled)
 result.invalidPreviewTotal=await page.locator('.total-line strong').innerText()
 assert.equal(result.invalidPreviewTotal,'--')
 // The HTML is rendered before Vue attaches input handlers; wait for its mounted fetch.
 const mountedProduct=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/product/1'&&response.status()===200)
 await page.goto(base+'/products/1',{waitUntil:'domcontentloaded'})
 await mountedProduct
 await page.locator('header .market-selector select').selectOption('CN')
 await page.waitForFunction(()=>document.querySelector('.product-info .current-price')?.textContent?.includes('1,889.93'))
 result.marketPrice=await page.locator('.product-info .current-price').innerText()
 assert.match(result.marketPrice,/CNY.*1,889\.93/)
 assert.match(await page.locator('html').getAttribute('lang'),/^en/)
 await page.locator('header .country-pill').click()
 await page.waitForTimeout(900)
 result.languagePrice=await page.locator('.product-info .current-price').innerText()
 assert.match(result.languagePrice,/CNY.*1,889\.93/)
 assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN')
 result.pageErrors=errors
 assert.equal(errors.length,0)
 result.passed=true
} catch(error) {result.passed=false;result.error=String(error);result.pageErrors=errors}
await fs.mkdir('output/cbjj-browser-qa',{recursive:true})
await fs.writeFile('output/cbjj-browser-qa/checkout.json',JSON.stringify(result,null,2))
await fs.writeFile('output/cbjj-browser-qa/checkout-api.json',JSON.stringify(api,null,2))
await page.screenshot({path:'output/cbjj-browser-qa/checkout.png',fullPage:true})
await browser.close()
console.log(JSON.stringify(result,null,2))
if(!result.passed) process.exitCode=1
