name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 如果你的主分支是 master，请将这里修改为 master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm exec --yes --package npm@11.12.1 -- npm ci

      - name: Generate static site
        run: npm run generate
        env:
          # 如果你的仓库名不是 username.github.io，而是类似于 my-project
          # 请取消下面这行的注释，并将 /my-project/ 替换为你的仓库名
          NUXT_APP_BASE_URL: /shop/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
